"use client";

import { useEffect, useState } from "react";
import { Braces, Check, Code2, Copy, Database, Download, FileCode2, FolderCode, Layers3, Mail, MapPin, Monitor, Plus, Server, ShieldCheck, Terminal, Zap } from "lucide-react";
import { Github, Linkedin } from "@/components/brand-icons";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { projects, profile } from "@/lib/portfolio";

const nav = [{ label: "Work", id: "work" }, { label: "Stack", id: "stack" }, { label: "About", id: "about" }, { label: "Contact", id: "contact" }];
const skills = [
  { number: "01", name: "Frontend", icon: Monitor, headline: "Interfaces people can use.", tech: ["React", "JavaScript", "HTML & CSS", "Tailwind CSS"], detail: "Components, forms, state and API integration. Responsive layouts with clear loading and error states." },
  { number: "02", name: "Backend", icon: Server, headline: "The logic behind the screen.", tech: ["Node.js", "Express", "REST APIs", "Mongoose"], detail: "CRUD endpoints, request validation, database integration and error handling." },
  { number: "03", name: "Data & tools", icon: Database, headline: "A foundation for every feature.", tech: ["MongoDB", "Git & GitHub", "Postman", "SQL fundamentals"], detail: "Document models, database queries, API testing and version control." },
  { number: "04", name: "Security foundation", icon: ShieldCheck, headline: "A closer look at the edge cases.", tech: ["OWASP Top 10", "Linux", "Networking", "bcrypt"], detail: "Hands-on security labs inform how I think about user input, password storage and access control." },
];

function Tags({ items }: { items: string[] }) { return <div className="tags">{items.map(item => <span key={item}>{item}</span>)}</div>; }

function ProjectDiagram({ type }: { type: string }) {
  if (type === "notes") return <div className="api-preview" aria-label="Notes App API overview"><div className="preview-caption"><Terminal size={16} /> notes.api <span>REST / CRUD</span></div><div className="api-row"><b className="get">GET</b><code>/api/notes</code><span>Read notes</span></div><div className="api-row"><b className="post">POST</b><code>/api/notes</code><span>Create a note</span></div><div className="api-row"><b className="patch">PATCH</b><code>/api/notes/:id</code><span>Edit a note</span></div><div className="api-row"><b className="delete">DELETE</b><code>/api/notes/:id</code><span>Delete a note</span></div><div className="preview-foot"><span>React</span><i /><span>Express</span><i /><span>MongoDB</span></div></div>;
  if (type === "travel") return <div className="travel-preview" aria-label="Bajrang Travels project features"><div className="preview-caption"><Layers3 size={16} /> bajrang.travels <span>BUSINESS WEBSITE</span></div><div className="travel-title">One place.<br /><em>Multiple services.</em></div><div className="service-list"><span>Travel enquiries</span><span>Appointments</span><span>Admin content</span></div><div className="preview-foot"><span>Next.js</span><i /><span>TypeScript</span><i /><span>Supabase</span></div></div>;
  return <div className="upload-preview" aria-label="User Management API workflow"><div className="preview-caption"><FileCode2 size={16} /> users.api <span>REGISTRATION / LOGIN</span></div><div className="upload-steps"><div><span>01</span><b>Register</b><small>User input</small></div><i /><div><span>02</span><b>bcrypt</b><small>Hash password</small></div><i /><div><span>03</span><b>MongoDB</b><small>Store record</small></div></div><div className="preview-foot"><span>Express + Mongoose + bcrypt</span></div></div>;
}

export default function Home() {
  const [activeSection, setActiveSection] = useState("");
  const [copied, setCopied] = useState(false);
  const [copyError, setCopyError] = useState(false);
  useEffect(() => {
    const observer = new IntersectionObserver(entries => { entries.forEach(entry => { if (entry.isIntersecting) setActiveSection(entry.target.id); }); }, { rootMargin: "-15% 0px -55% 0px" });
    nav.forEach(item => { const section = document.getElementById(item.id); if (section) observer.observe(section); });
    return () => observer.disconnect();
  }, []);
  async function copyEmail() { try { await navigator.clipboard.writeText(profile.email); setCopied(true); setCopyError(false); } catch { setCopyError(true); } }

  return <>
    <a className="skip-link" href="#main">Skip to content</a>
    <header className="site-header"><div className="header-inner"><a className="wordmark" href="#main" aria-label="Suryadeep Jadeja home"><span className="monogram">sj<span>.</span></span><span className="wordmark-name">suryadeep<span>jadeja</span></span></a><nav aria-label="Main navigation">{nav.map(item => <a key={item.id} href={`#${item.id}`} className={activeSection === item.id ? "active" : ""} aria-current={activeSection === item.id ? "location" : undefined}>{item.label}</a>)}</nav><a className="header-contact" href={`mailto:${profile.email}`}><Mail size={16} /><span>Let’s talk</span></a></div></header>
    <main id="main">
      <section className="hero container" aria-labelledby="hero-title"><div className="hero-copy"><p className="eyebrow"><span className="small-line" /> MERN STACK DEVELOPER</p><p className="hero-intro">Hi, I’m Suryadeep Jadeja.</p><h1 id="hero-title">From interface<br />to <span>API.</span></h1><p className="hero-description">I build React interfaces and Node.js APIs, with MongoDB for data and a growing focus on application security.</p><div className="hero-actions"><a className="button button-primary" href="#work"><FolderCode size={18} />Explore my work</a><a className="button button-outline" href="/suryadeep-jadeja-resume.pdf" download><Download size={18} />Download résumé</a></div><div className="hero-meta"><span><MapPin size={15} />Jamnagar, Gujarat</span><span>MCA · 2026–2028</span></div></div><div className="hero-system"><div className="system-grid" aria-hidden="true" /><div className="system-top"><span>THE MERN STACK</span><span>FOUR PARTS. ONE APPLICATION.</span></div><div className="stack-diagram" aria-label="MERN architecture: React interface, Node.js runtime, Express API, MongoDB database"><div className="stack-node node-react"><div className="node-icon"><Braces size={27} /></div><small>INTERFACE</small><h2>React</h2><p>What the user sees.</p></div><div className="stack-node node-node"><div className="node-icon"><Terminal size={27} /></div><small>RUNTIME</small><h2>Node.js</h2><p>Where the server runs.</p></div><div className="stack-node node-express"><div className="node-icon"><Server size={27} /></div><small>API</small><h2>Express</h2><p>How requests flow.</p></div><div className="stack-node node-mongo"><div className="node-icon"><Database size={27} /></div><small>DATABASE</small><h2>MongoDB</h2><p>Where the data lives.</p></div></div><div className="system-bottom"><Code2 size={16} /><span>Frontend. Backend. Connected.</span><span className="system-index">01—04</span></div></div></section>
      <div className="position-strip"><div className="container strip-inner"><span><span className="availability-dot" />Open to MERN internships & junior opportunities</span><a href="#contact">Let’s find a good fit <Plus size={16} /></a></div></div>
      <section id="work" className="section container" aria-labelledby="work-title"><div className="section-heading"><div><p className="eyebrow">01 / SELECTED WORK</p><h2 id="work-title">Ideas, made tangible<span>.</span></h2></div><p>A closer look at what I’ve built,<br className="desktop-break" /> how it works, and what comes next.</p></div><div className="project-grid">{projects.map((project, index) => <article key={project.id} className={`project-card project-${project.id}`}><ProjectDiagram type={project.id} /><div className="project-body"><div className="project-meta"><span>0{index + 1} / {project.kind}</span><span className={`project-status ${project.id === "image" ? "status-progress" : ""}`}>{project.status}</span></div><h3>{project.name}</h3><p>{project.summary}</p><Tags items={project.stack} /><div className="project-actions"><Dialog><DialogTrigger asChild><button className="case-study-button">Project details <Plus size={17} /></button></DialogTrigger><DialogContent className="case-dialog"><DialogHeader><p className="eyebrow">{project.kind} / {project.status}</p><DialogTitle className="case-title">{project.name}</DialogTitle><DialogDescription className="case-description">{project.summary}</DialogDescription></DialogHeader><Tags items={project.stack} /><div className="case-sections"><div><h3>The problem</h3><p>{project.problem}</p></div><div><h3>My work</h3><ul>{project.contributions.map(item => <li key={item}><Check size={15} /><span>{item}</span></li>)}</ul></div><div><h3>Engineering decisions</h3><p>{project.decisions}</p></div><div><h3>Current status</h3><p>{project.current}</p></div></div><div className="case-links">{project.demo && <a className="button button-primary" href={project.demo} target="_blank" rel="noopener noreferrer"><Monitor size={17} />Visit project</a>}{project.source && <a className="button button-outline" href={project.source} target="_blank" rel="noopener noreferrer"><Github size={17} />View source</a>}<a className="button button-outline" href={`mailto:${profile.email}?subject=${encodeURIComponent(`Portfolio walkthrough: ${project.name}`)}`}><Mail size={17} />Discuss this project</a></div></DialogContent></Dialog>{project.demo && <a href={project.demo} target="_blank" rel="noopener noreferrer" className="project-external" aria-label={`Visit ${project.name}`}><Monitor size={18} /></a>}{project.source && <a href={project.source} target="_blank" rel="noopener noreferrer" className="project-external" aria-label={`View ${project.name} source on GitHub`}><Github size={18} /></a>}</div></div></article>)}</div><div className="work-note"><Github size={17} /><p>More experiments and learning in public.</p><a href={profile.github} target="_blank" rel="noopener noreferrer">Explore my GitHub</a></div></section>
      <section id="stack" className="section stack-section" aria-labelledby="stack-title"><div className="container"><div className="section-heading"><div><p className="eyebrow">02 / SKILLS & FOUNDATIONS</p><h2 id="stack-title">The tools behind the work<span>.</span></h2></div><p>Learning through building,<br className="desktop-break" /> one complete feature at a time.</p></div><div className="skills-grid">{skills.map(skill => <article className="skill-card" key={skill.number}><div className="skill-top"><skill.icon size={24} /><span>{skill.number}</span></div><p className="skill-category">{skill.name}</p><h3>{skill.headline}</h3><p className="skill-detail">{skill.detail}</p><Tags items={skill.tech} /></article>)}</div><div className="learning-line"><Zap size={17} /><p><strong>Currently deepening:</strong> React patterns, authentication, image uploads and application security.</p></div></div></section>
      <section id="about" className="section container about-section" aria-labelledby="about-title"><div className="about-copy"><p className="eyebrow">03 / A LITTLE ABOUT ME</p><h2 id="about-title">Curious by nature.<br />A developer by practice<span>.</span></h2><p>I’m Suryadeep Sinh Jadeja, a BCA graduate now pursuing my MCA in Jamnagar. My focus is MERN development: connecting usable interfaces with the APIs and data behind them.</p><p>I came to web development with a cybersecurity foundation. Working through SQL injection, XSS and OWASP labs made me more interested in how applications behave—and how they can fail.</p><p>I use AI to explore ideas, design and develop, while continuing to learn the code and decisions behind my projects.</p><div className="about-links"><a href={profile.linkedin} target="_blank" rel="noopener noreferrer"><Linkedin size={18} />LinkedIn</a><a href={profile.github} target="_blank" rel="noopener noreferrer"><Github size={18} />GitHub</a></div></div><div className="about-sidebar"><div className="education-card"><p className="eyebrow">EDUCATION</p><div className="education-item"><div><span className="education-date">2026—2028</span><span className="education-current">In progress</span></div><h3>Master of Computer Applications</h3><p>Haria College / JVIMS<br />Jamnagar, Gujarat</p></div><div className="education-item"><span className="education-date">Completed 2026</span><h3>Bachelor of Computer Applications</h3><p>Saurashtra University<br />Rajkot, Gujarat</p></div></div><div className="security-note"><ShieldCheck size={24} /><h3>Security informs how I build.</h3><p>My foundation includes Linux, networking and practical web security labs. I’m bringing that perspective into my MERN work.</p></div></div></section>
      <section id="contact" className="contact-section" aria-labelledby="contact-title"><div className="container contact-inner"><div><p className="eyebrow">04 / LET’S CONNECT</p><h2 id="contact-title">Your next developer<br />could start <span>here.</span></h2><p>Hiring for a MERN internship or junior role?<br />I’d love to talk about your team and show you my work.</p><div className="contact-actions"><a className="button button-primary" href={`mailto:${profile.email}?subject=${encodeURIComponent("MERN opportunity — Suryadeep Jadeja")}`}><Mail size={18} />Email me</a><a className="button button-outline" href={profile.linkedin} target="_blank" rel="noopener noreferrer"><Linkedin size={18} />Connect on LinkedIn</a></div></div><div className="contact-card"><span className="eyebrow">DIRECT CONTACT</span><a className="email-address" href={`mailto:${profile.email}`}>{profile.email}</a><button className="copy-button" onClick={copyEmail}>{copied ? <Check size={17} /> : <Copy size={17} />}{copied ? "Email copied" : "Copy email address"}</button><p className="copy-feedback" role="status" aria-live="polite">{copyError ? "Select the email above to open your mail app." : copied ? "Ready to paste into your email app." : ""}</p><div className="contact-facts"><div><span>Based in</span><b>Jamnagar, India</b></div><div><span>Focus</span><b>MERN development</b></div><div><span>Looking for</span><b>Internships & junior roles</b></div></div><a className="resume-link" href="/suryadeep-jadeja-resume.pdf" download><Download size={17} />Download my résumé</a></div></div></section>
    </main><footer className="container site-footer"><a className="footer-brand" href="#main">suryadeep<span>.</span></a><p>© 2026 Suryadeep Jadeja</p><div><a href={profile.github} target="_blank" rel="noopener noreferrer" aria-label="GitHub"><Github size={18} /></a><a href={profile.linkedin} target="_blank" rel="noopener noreferrer" aria-label="LinkedIn"><Linkedin size={18} /></a><a href={`mailto:${profile.email}`} aria-label="Email"><Mail size={18} /></a></div></footer>
  </>;
}
