export const profile = {
  name: "Suryadeep Sinh Jadeja",
  email: "rmjadeja142@gmail.com",
  github: "https://github.com/suryadeep-sec",
  linkedin: "https://www.linkedin.com/in/suryadeep-jadeja-415973371/",
};
export type Project = { id: string; name: string; kind: string; status: string; summary: string; stack: string[]; problem: string; contributions: string[]; decisions: string; current: string; demo?: string; source?: string; };
export const projects: Project[] = [
  { id: "notes", name: "MERN Notes App", kind: "Full-stack application", status: "CRUD complete", summary: "Create, read, edit and delete notes through a React interface connected to an Express API and MongoDB.", stack: ["React", "Node.js", "Express", "MongoDB"], problem: "Keep notes in a database and make everyday editing available through a simple web interface.", contributions: ["Built React forms and connected them to CRUD endpoints.", "Created Express routes for listing, retrieving, creating, editing and deleting notes.", "Used Mongoose models to persist title and description in MongoDB.", "Added required-field validation and API error responses."], decisions: "The frontend communicates with REST endpoints. Express handles requests and validation, while Mongoose manages the note model and MongoDB operations. PATCH is used for updates, with schema validators enabled.", current: "The core CRUD flow is functional. Registration and authentication are being developed. A public repository and hosted demo are not yet linked; contact me for a walkthrough." },
  { id: "travel", name: "Bajrang Travels", kind: "Business website", status: "Business project", summary: "A travel and digital service website with service listings, appointment enquiries and an admin content interface.", stack: ["Next.js", "TypeScript", "Tailwind CSS", "Supabase"], problem: "Bring a service business’s offerings and enquiry flow into one website, with a separate interface for managing its content.", contributions: ["Built service, about, FAQ, contact and appointment pages.", "Created an admin interface for services, FAQs, enquiries and reviews.", "Connected content and enquiry routes to Supabase queries.", "Used React, TypeScript and Tailwind CSS across the interface."], decisions: "This project uses Next.js and Supabase instead of MongoDB and Express. It complements my MERN work by demonstrating React-based page development, database-backed content and separate customer and admin interfaces.", current: "The project source and previously deployed website are linked below. The implementation includes customer-facing pages and an admin content interface.", demo: "https://bajrang-travels-one.vercel.app/", source: "https://github.com/suryadeep-sec/bajrang-travels" },
  { id: "users", name: "User Management API", kind: "Backend application", status: "Learning project", summary: "A registration and login API exploring user records, MongoDB integration and password hashing.", stack: ["Node.js", "Express", "Mongoose", "bcrypt"], problem: "Create a backend foundation for registering users and checking login credentials without storing plain-text passwords.", contributions: ["Built a registration endpoint in Express.", "Stored user records through a Mongoose model in MongoDB.", "Used bcrypt to hash passwords before storing them.", "Built and practised the login API flow."], decisions: "Password hashing is handled by bcrypt, and user records are persisted through Mongoose. I used this project to practise the registration and login foundations before extending my MERN applications.", current: "A functional registration/login learning project. Public source and a hosted demo are not yet linked; contact me for a walkthrough." },
];
